### PR TITLE
Add more browsers for e2e tests

### PR DESCRIPTION
**Pull request by mrdrogdrog**
### Component/Part
E2E tests

### Description
This PR adds safari and edge for e2e tests

### Steps

- [x] added implementation
- [x] added / updated tests
- [x] added / updated documentation
- [x] extended changelog

### Related Issue(s)
#364

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I am not sure how Chrome does things on the different platforms and if it would be necessary to test it on all platforms.

**Comment by mrdrogdrog** [comment]
The chrome engine (blink) should behave in the same way on every platform.

**Comment by mrdrogdrog** [comment]
Oookay.. MacOS keeps failing because it can't connect to the package registry and Windows keeps failing because the package pipeline is not meant to be run on windows. It fails e.g. with the tar command.

**Comment by mrdrogdrog** [comment]
PR closed. For Reason read the issue.

**Comment by SuperSandro2000** [comment]
Actually safari is not supported and not really prioritized https://github.com/cypress-io/cypress/issues/6422

```
Can't run because you've entered an invalid browser name.

Browser: 'safari' was not found on your system or is not supported by Cypress.

Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox (Cypress support in beta)

You can also use a custom browser: https://on.cypress.io/customize-browsers

Available browsers found on your system are:
- chrome
- firefox
- edge
- electron
```

**Pull request closed without merging**
