### PR TITLE
added support for markdown-it-footnote

### PR DESCRIPTION
**Pull request by DerMolly**
### Component/Part
markdown renderer

### Description
This PR makes it possible to use footnotes

grafik

### Steps

- [x] added implementation
- [x] added / updated tests
- [x] added / updated documentation
- [x] extended changelog

### CODE REVIEW

**Comment by ErikMichelson** [comment]
Why is the first word after the footnote declaration highlighted?

**Comment by DerMolly** [comment]
You mean Placeholder? Because that's a heading?

**Comment by ErikMichelson** [comment]
Nope, I'm referring to the blue word "Footnote" in line 8 and 10 of the example. It doesn't look like if it's intended.

**Comment by mrdrogdrog** [comment]
It is intended. It's the same behaviour as in 1.6

**Pull request merged**
