### PR TITLE
add YAML Metadata

### PR DESCRIPTION
**Pull request by DerMolly**
### Component/Part
markdown renderer

### Description
This PR adds the ability to parse YAML Metadata at the beginning of the markdown file

### Steps

- [x] added implementation
- [x] added / updated tests
- [x] added / updated documentation
- [x] extended changelog

### Related Issue(s)
#244

### CODE REVIEW

**Comment by mrdrogdrog** [comment]
I think we should use deep-equal instead of the self made function

**Comment by DerMolly** [comment]
further reading about deep-equal vs. json.stringfy https://www.mattzeunert.com/2016/01/28/javascript-deep-equal.html

**Comment by DerMolly** [comment]
Maybe this can help with the open graph types https://github.com/beau6183/ts-open-graph-scraper/blob/master/src/types.ts

**Comment by ErikMichelson** [comment]
I thought about letting them as an `Map<string,string>` since we don't access these og-attributes directly.

**Comment by ErikMichelson** [comment]
As the code of this PR was heavily changed in #310, it doesn't make sense to continue here. The changes will be included in #310 instead.

**Pull request closed without merging**
