### PR TITLE
added redirector component

### PR DESCRIPTION
**Pull request by DerMolly**
it will redirect every request to /$something that is not handled otherwise (/intro, /login and such) to /n/$something

Signed-off-by: Philip Molares <philip.molares@udo.edu>

### CODE REVIEW

**Comment by ErikMichelson** [comment]
I don't think that redirecting everything to /n/ is a great idea. If I remember correctly the idea in one of the last community calls was to only redirect pre-2.0-notes to the new namespace.
For all other requests that don't match an existent route, I would throw a 404.

**Comment by DerMolly** [comment]
How would we identify only pre-2.0-notes and nothing else?

**Comment by ErikMichelson** [comment]
The idea was to add another column to the notes table that indicates whether a note is created before the 2.0 update of after that.

**Comment by DerMolly** [comment]
I did not remember that, but that's a good idea I will add the according code.

**Pull request merged**
