### PR TITLE
Add types to tsconfig.json

### PR DESCRIPTION
**Pull request by mrdrogdrog**
### Component/Part
TypeScript Editor

### Description
This PR adds our own types to the tsconfig

### Steps

- [x] added implementation
- [x] added / updated tests
- [x] added / updated documentation
- [x] extended changelog

### CODE REVIEW

**Comment by mrdrogdrog** [comment]
It's your change. I extracted it from https://github.com/codimd/react-client/pull/311

**Comment by DerMolly** [comment]
Then is a separate PR kinda unnecessary as this is specifically needed because of the fullscreen addon typing I wrote for codemirror.

**Comment by mrdrogdrog** [comment]
Well this way it's more correct.

**Comment by mrdrogdrog** [comment]
Not necessary anymore.

**Pull request closed without merging**
